### ISSUE TITLE
Not everyone has an apple developer account.

### ISSUE THREAD

**Issue by takasurazeem** [MrAsterisco/Gymspot#11]
Hey, this is a wonderful project, but not everyone has an active apple developer account, which is one blocker for many contributors like myself. I have attached a screenshot for Login/Signup with the email feature concept, would you like to discuss it in greater detail? 

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2876680/203211664-64eab4a2-86db-42f3-a716-814ac4dc527a.png">

**Comment by MrAsterisco** [comment]
Hey @takasurazeem ! Thanks for reaching out. You don't need an active developer account to login into the app. You just need an Apple ID.
You will need an active developer account to deploy the app on a physical device, though.

The reason why only Sign in with Apple is supported right now is just a matter of time availability: I wanted to implement the simplest method first, just to be able to authenticate users with Firebase.
